# Generated by Django 4.0.4 on 2022-05-02 08:26

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Browser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('wsEndpoint', models.CharField(blank=True, help_text='address of the running browser', max_length=255)),
            ],
            options={
                'verbose_name': 'Browser',
                'verbose_name_plural': 'Browsers',
            },
        ),
        migrations.CreateModel(
            name='ParserSettings',
            fields=[
                ('preferences_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='preferences.preferences')),
                ('max_tab_deepl', models.PositiveSmallIntegerField(default=4, help_text='how many tabs will be open for the deepl translator')),
                ('max_tab_google', models.PositiveSmallIntegerField(default=4, help_text='how many tabs will be open for the google translator')),
                ('max_tab_yandex', models.PositiveSmallIntegerField(default=4, help_text='how many tabs will be open for the yandex translator')),
                ('max_tab_yandex_image', models.PositiveSmallIntegerField(default=4, help_text='how many tabs will be open for the yandex-image translator')),
            ],
            options={
                'verbose_name': 'ParserSettings',
                'verbose_name_plural': 'ParserSettings',
            },
            bases=('preferences.preferences',),
            managers=[
                ('singleton', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='TranslateParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='unique key for url generation')),
                ('url', models.CharField(help_text='translator website', max_length=255)),
                ('browser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.browser')),
            ],
            options={
                'verbose_name': 'TranslateParser',
                'verbose_name_plural': 'TranslateParsers',
            },
        ),
        migrations.CreateModel(
            name='TranslateImageParser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(blank=True, help_text='unique key for url generation')),
                ('url', models.CharField(help_text='image translator website', max_length=255)),
                ('file_input', models.CharField(help_text='file input selector', max_length=255)),
                ('browser', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.browser')),
            ],
            options={
                'verbose_name': 'TranslateImageParser',
                'verbose_name_plural': 'TranslateImageParsers',
            },
        ),
        migrations.CreateModel(
            name='Parser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('type', models.CharField(choices=[('Translate', 'Translate'), ('TranslateImage', 'Translate Image'), ('Novel', 'Novel'), ('Manga', 'Manga')], max_length=50)),
                ('translate_image_parser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.translateimageparser')),
                ('translate_parser', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.translateparser')),
            ],
            options={
                'verbose_name': 'Parser',
                'verbose_name_plural': 'Parsers',
            },
        ),
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('in_use', models.BooleanField(default=False)),
                ('index', models.PositiveSmallIntegerField(help_text="position at the browser's page list", unique=True)),
                ('browser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.browser')),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.parser')),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Pages',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=100, verbose_name='Language name')),
                ('code', models.CharField(max_length=10, verbose_name='Language code')),
                ('source', models.CharField(blank=True, help_text='language selector from the drop-down menu', max_length=255)),
                ('destination', models.CharField(blank=True, help_text='language selector from the drop-down menu', max_length=255)),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.parser')),
            ],
            options={
                'verbose_name': 'Language',
                'verbose_name_plural': 'Languages',
            },
        ),
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('captcha_button', models.CharField(help_text="captcha button selector(i'm not robot)", max_length=255)),
                ('captcha_image', models.CharField(help_text='captcha image selector', max_length=255)),
                ('captcha_input', models.CharField(help_text='captcha input selector', max_length=255)),
                ('captcha_result_button', models.CharField(help_text='captcha result button selector', max_length=255)),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.parser')),
            ],
            options={
                'verbose_name': 'Captcha',
                'verbose_name_plural': 'Captcha',
            },
        ),
        migrations.CreateModel(
            name='Block',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('name', models.CharField(max_length=255, verbose_name='block name')),
                ('description', models.CharField(blank=True, max_length=255)),
                ('css_selector', models.CharField(max_length=255, verbose_name='block css selector')),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.parser')),
            ],
            options={
                'verbose_name': 'Block',
                'verbose_name_plural': 'Blocks',
            },
        ),
    ]
