# Generated by Django 4.0.4 on 2022-05-06 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0002_parsersettings_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='fails_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='the count of fails to get translate from the page'),
        ),
        migrations.AlterField(
            model_name='parser',
            name='type',
            field=models.CharField(choices=[('Translate', 'Translate'), ('TranslateImage', 'Translate Image')], max_length=50),
        ),
    ]
