# Generated by Django 4.0.4 on 2022-05-07 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0004_novelparser_alter_parser_type_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='parser',
            name='novel_parser',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parsers.novelparser'),
        ),
    ]
