# Generated by Django 4.0.4 on 2022-05-07 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0005_parser_novel_parser'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='blocks',
            field=models.ManyToManyField(to='parsers.block'),
        ),
    ]
