# Generated by Django 4.0.4 on 2022-05-07 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0006_resource_blocks'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelparser',
            name='browser',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.browser'),
        ),
        migrations.AlterField(
            model_name='novelparser',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='novelparser',
            name='slug',
            field=models.SlugField(blank=True, help_text='unique key for url generation'),
        ),
    ]
