# Generated by Django 4.0.4 on 2022-05-08 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0008_sitelanguage'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitelanguage',
            name='flag',
            field=models.ImageField(blank=True, help_text='language flags', null=True, upload_to='language_flags/'),
        ),
        migrations.AddField(
            model_name='sitelanguage',
            name='name',
            field=models.CharField(blank=True, help_text='language name', max_length=100),
        ),
        migrations.AlterField(
            model_name='resource',
            name='blocks',
            field=models.ManyToManyField(blank=True, to='parsers.block'),
        ),
    ]
