# Generated by Django 4.0.4 on 2022-05-08 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0010_remove_resource_blocks_block_resource_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='browser',
            name='type',
            field=models.CharField(choices=[('Translate', 'Translate'), ('Novel', 'Novel')], default='Translate', max_length=50),
            preserve_default=False,
        ),
    ]
