# Generated by Django 4.0.4 on 2022-05-09 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0013_resource_intercept_page_res'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='intercept_page_res',
            field=models.CharField(blank=True, help_text='put the types of resources that should not be loaded through "_"<br> for example: img_css<br>resource types: css, img, font, fetch, media, js', max_length=100),
        ),
        migrations.CreateModel(
            name='SearchTitle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('search_query_param', models.CharField(blank=True, max_length=100)),
                ('parser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parsers.parser')),
            ],
            options={
                'verbose_name': 'SearchTitle',
                'verbose_name_plural': 'SearchTitle',
            },
        ),
    ]
