# Generated by Django 4.0.4 on 2022-05-09 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0014_alter_resource_intercept_page_res_searchtitle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchtitle',
            name='parser',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='parsers.parser'),
        ),
    ]
