# Generated by Django 4.0.4 on 2022-05-09 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0015_alter_searchtitle_parser'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SearchTitle',
            new_name='Search',
        ),
        migrations.AlterModelOptions(
            name='search',
            options={'verbose_name': 'Search', 'verbose_name_plural': 'Search'},
        ),
    ]
