# Generated by Django 4.0.4 on 2022-05-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0016_rename_searchtitle_search_alter_search_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='urn_regex',
            field=models.CharField(blank=True, help_text='necessary to resource search by income url', max_length=255),
        ),
        migrations.AlterField(
            model_name='resource',
            name='intercept_page_res',
            field=models.CharField(blank=True, help_text='put the types of resources that should not be loaded through "_"<br> for example: img_css_fetch_media_font_js<br>resource types: css, img, font, fetch, media, js', max_length=100),
        ),
    ]
