# Generated by Django 4.0.4 on 2022-05-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0017_resource_urn_regex_alter_resource_intercept_page_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='is_bare_text',
            field=models.BooleanField(default=False, help_text='if it have "bare text" then we should exclude other tags to get the proper innerText'),
        ),
    ]
