# Generated by Django 4.0.4 on 2022-05-11 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0018_block_is_bare_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='is_bare_text',
        ),
        migrations.AddField(
            model_name='block',
            name='exclude_tags',
            field=models.BooleanField(default=False, help_text='if it has "bare text" then we should exclude other tags to get the proper innerText'),
        ),
    ]
