# Generated by Django 4.0.4 on 2022-05-11 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0019_remove_block_is_bare_text_block_exclude_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='use_POST',
            field=models.BooleanField(default=False, help_text='use POST request to search'),
        ),
    ]
