# Generated by Django 4.0.4 on 2022-05-12 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0020_search_use_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='search',
            name='encoding',
            field=models.CharField(blank=True, help_text='encode param by encoding scheme. for example: UTF-8 or GB2312. leave blank if doesnt need encoding.', max_length=20),
        ),
        migrations.AlterField(
            model_name='resource',
            name='intercept_page_res',
            field=models.CharField(blank=True, help_text='put the types of resources that should not be loaded through "_"<br> for example: img_css_fetch_media_font_js<br>resource types: css, img, font, fetch, media, js, ', max_length=100),
        ),
    ]
