# Generated by Django 4.0.4 on 2022-05-13 19:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0021_search_encoding_alter_resource_intercept_page_res'),
    ]

    operations = [
        migrations.AddField(
            model_name='novelparser',
            name='main_language',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='parsers.sitelanguage'),
        ),
    ]
