# Generated by Django 4.0.4 on 2022-05-13 19:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0022_novelparser_main_language'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitelanguage',
            name='parser',
        ),
    ]
