# Generated by Django 4.0.4 on 2022-05-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0025_alter_page_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='page_id',
            field=models.CharField(default=1, help_text='page id from the browser', max_length=100),
            preserve_default=False,
        ),
    ]
