# Generated by Django 4.0.4 on 2022-05-26 20:09

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0026_remove_page_index_page_page_id'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='page',
            name='browser_page_index_unique',
        ),
        migrations.AddConstraint(
            model_name='page',
            constraint=models.UniqueConstraint(django.db.models.expressions.F('browser'), django.db.models.expressions.F('page_id'), name='browser_page_id_unique'),
        ),
    ]
