# Generated by Django 4.0.4 on 2022-05-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0027_remove_page_browser_page_index_unique_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='index',
        ),
    ]
