# Generated by Django 4.0.4 on 2022-05-30 10:17

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parsers', '0028_remove_page_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parsersettings',
            name='max_tab_deepl',
        ),
        migrations.RemoveField(
            model_name='parsersettings',
            name='max_tab_google',
        ),
        migrations.RemoveField(
            model_name='parsersettings',
            name='max_tab_yandex',
        ),
        migrations.RemoveField(
            model_name='parsersettings',
            name='max_tab_yandex_image',
        ),
        migrations.AddField(
            model_name='parser',
            name='max_pages_count',
            field=models.PositiveSmallIntegerField(default=0, help_text='if set 0 the default value will be used', validators=[django.core.validators.MaxValueValidator(8)]),
        ),
        migrations.AddField(
            model_name='parser',
            name='timeout',
            field=models.PositiveSmallIntegerField(default=0, help_text='if set 0 the default value will be used', validators=[django.core.validators.MaxValueValidator(60)], verbose_name='Timeout in seconds'),
        ),
        migrations.AddField(
            model_name='parsersettings',
            name='max_tabs',
            field=models.PositiveSmallIntegerField(default=4, help_text='how many tabs will be open for the services'),
        ),
    ]
